### ISSUE TITLE
PORTABILITY: Package assumes GNU make

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/affxparser#10]
```
* checking for GNU extensions in Makefiles ... WARNING
Found the following file(s) containing GNU extensions:
  src/Makevars
Portable Makefiles do not use GNU extensions such as +=, :=, $(shell),
$(wildcard), ifeq ... endif. See section ‘Writing portable packages’ in
the ‘Writing R Extensions’ manual.
```
More details https://travis-ci.org/HenrikBengtsson/affxparser/jobs/47449797

This is currently "solved" by adding the following to the DESCRIPTION file:
```
SystemRequirements: GNU make
```
such that `R CMD check` instead gives:
```
* checking for GNU extensions in Makefiles ... NOTE
GNU make is a SystemRequirements.
```
which may be an unnecessary restriction.  Is there a simple fix?

**Comment by HenrikBengtsson** [comment]
The offending lines are in [`src/Makefile`](https://github.com/HenrikBengtsson/affxparser/blob/master/src/Makevars#L7):
```
L7: PKG_CPPFLAGS+=\ 
```
and in [`src/Makefile.win`](https://github.com/HenrikBengtsson/affxparser/blob/master/src/Makevars.win#L9):
```
L1: PKG_LIBS+=-lws2_32
...
L9: PKG_CPPFLAGS+=\ 
```

**Comment by HenrikBengtsson** [comment]
Try to replace the above with:
```
L1: PKG_LIBS=$(PKG_LIBS) -lws2_32
...
L9: PKG_CPPFLAGS=$(PKG_CPPFLAGS)\ 
```
gives
```
Makevars.win:7: *** Recursive variable `PKG_CPPFLAGS' references itself (eventually).  Stop.
```
on Windows.

**Comment by HenrikBengtsson** [comment]
The [solution](https://www.gnu.org/software/make/manual/html_node/Error-Messages.html) is to use:

> [...] use simply-expanded variables (‘:=’ or ‘::=’) or use the append operator (‘+=’)

Furthermore, the GNU make documentation suggests to use `::=` (and not `:=`), [because](https://www.gnu.org/software/make/manual/html_node/Flavors.html#Flavors):

> Simply expanded variables are defined by lines using ‘:=’ or ‘::=’ (see Setting Variables). Both forms are equivalent in GNU make; however only the ‘::=’ form is described by the POSIX standard (support for ‘::=’ was added to the POSIX standard in 2012, so older versions of make won’t accept this form either).

However, trying with:
```
PKG_CPPFLAGS ::= $(PKG_CPPFLAGS) \ 
```
gives `R CMD INSTALL` error:
```
make: *** No rule to make target `=', needed by `PKG_CPPFLAGS'.  Stop.
```
on both Linux and Windows whereas
```
PKG_CPPFLAGS := $(PKG_CPPFLAGS) \ 
```
works!

**Comment by kasperdanielhansen** [comment]
You can have great fun submitting a bug report complaining why R does not
support a POSIX standard in its make system :)

Or you can be happy its working :)

**Comment by HenrikBengtsson** [comment]
Yeah, I know.  I think I stay quiet :)

BTW, `Makevars` is an R invention, correct?  I cannot find any documentation on it outside R.

**Comment by kasperdanielhansen** [comment]
I think so.

**Comment by HenrikBengtsson** [comment]
Argh, too soon, it worked, but only because I forgot to remove 'SystemRequirements: GNU make`. So now we're back to:
```r
* checking for GNU extensions in Makefiles ... WARNING
Found the following file(s) containing GNU extensions:
  src/Makevars
Portable Makefiles do not use GNU extensions such as +=, :=, $(shell),
$(wildcard), ifeq ... endif. See section 'Writing portable packages' in
the 'Writing R Extensions' manual.
```

**Comment by HenrikBengtsson** [comment]
I think I finally solved this; we never needed:
```
PKG_LIBS := $(PKG_LIBS) -lws2_32
```
It was enough with
```
PKG_LIBS = -lws2_32
```
See commit 6478d11.  All [Bioc checks](http://master.bioconductor.org/checkResults/devel/bioc-LATEST/affxparser/) and [Travis CI](https://travis-ci.org/HenrikBengtsson/affxparser) checks gives OK for this approach.
