### ISSUE TITLE
memory errors

### ISSUE THREAD

**Issue by kasperdanielhansen** [HenrikBengtsson/affxparser#14]
(from Tomas Kalibera @kalibera)

I am working on a static checking tool that is looking for memory
protection errors in R packages.
I think I found some in the affxparser package:

- src/R_affx_chp_parser.cpp, in R_affx_ReadCHP, around [line 770](https://github.com/HenrikBengtsson/affxparser/blob/master/src/R_affx_chp_parser.cpp#L768)
should be UNPROTECT(3) instead of UNPROTECT(2) ?

- src/R_affx_chp_parser.cpp, in R_affx_GetCHPEntries, around [line 562](https://github.com/HenrikBengtsson/affxparser/blob/master/src/R_affx_chp_parser.cpp#L562)
should be UNPROTECT(6) instead of UNPROTECT(5) ?

- src/R_affx_chp_parser.cpp, in R_affx_GetCHPGenotypingResults, around [line 339](https://github.com/HenrikBengtsson/affxparser/blob/master/src/R_affx_chp_parser.cpp#L339)
the argument of PrintValue has to be protected

    Rf_PrintValue(mkString("dudey"))

    the temporary string "dudey" could be destroyed within PrintValue before being printed

- the same error around [line 348](https://github.com/HenrikBengtsson/affxparser/blob/master/src/R_affx_chp_parser.cpp#L562)

Best

**Comment by HenrikBengtsson** [comment]
Thanks @kalibera.  I've also seen you're contributions to R code - thanks a bunch.  We'll fix this.

**Comment by HenrikBengtsson** [comment]
Fixed in affxparser 1.41.1 which is now available on [Bioc devel](http://www.bioconductor.org/packages/devel/bioc/html/affxparser.html).
