### ISSUE TITLE
hta20_Hs_ENTREZG.cdf causes readCdfNNN() to core dump

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/affxparser#18]
The v3/text CDF file [hta20_Hs_ENTREZG.cdf](http://mbni.org/customcdf/19.0.0/entrezg.download/hta20_Hs_ENTREZG_19.0.0.zip) file  (239,964,329 bytes; md5 82f6db63918c88fa54e0ce06096564ef) causes `readCdf()` etc to core dump.  It works to read the CDF header though.  Example:

```r
> pathname <- "hta20_Hs_ENTREZG.cdf"
> file.info(pathname)$size
[1] 239964329
> digest::digest(file=pathname)
[1] "82f6db63918c88fa54e0ce06096564ef"
```
```sh
$ grep -E "^\[Unit[^]_]+\]" hta20_Hs_ENTREZG.cdf | wc
  26876   26876  340732
$ grep -E "^\[Unit[^]]+_[^]]+\]" hta20_Hs_ENTREZG.cdf | wc
  26876   26876  528864
```

Reading CDF header works:
```r
> library(affxparser)
> hdr <- readCdfHeader(pathname)
> str(hdr)
List of 12
 $ ncols      : int 2680
 $ nrows      : int 2572
 $ nunits     : int 26876
 $ nqcunits   : int 0
 $ refseq     : chr ""
 $ chiptype   : chr "hta20_Hs_ENTREZG"
 $ filename   : chr "./hta20_Hs_ENTREZG.cdf"
 $ rows       : int 2572
 $ cols       : int 2680
 $ probesets  : int 26876
 $ qcprobesets: int 0
 $ reference  : chr ""
```
Anything else will core dump R (both on Windows and Linux and with affxparser 1.40.0 and 1.41.2), e.g.
```r
> data <- readCdf(pathname)

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("R_affx_get_cdf_file", filename, as.integer(units), as.integer(verbose),     returnUnitType, returnUnitDirection, returnUnitAtomNumbers,     returnUnitNumber, returnXY, returnIndices, returnBases, returnAtoms,     returnIndexpos, returnIsPm, returnBlockDirection, returnBlockAtomNumbers,     PACKAGE = "affxparser")
 2: readCdf(pathname, verbose = -100)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
aborting ...
Segmentation fault (core dumped)
```

**Comment by HenrikBengtsson** [comment]
FYI, @benilton.

**Comment by HenrikBengtsson** [comment]
Searching for another CDF for this chip type, I found the text/v3 CDF file [GPL18588_hta20_Hs_ENTREZG.cdf](ftp://ftp.ncbi.nlm.nih.gov/geo/platforms/GPL18nnn/GPL18588/suppl/GPL18588_hta20_Hs_ENTREZG.cdf.gz) (236,635,269 bytes; md5: b3890b60f699ebf53f9eea199ac4fbfe) from http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL18588, which works:
```r
> library(affxparser)
> pathname <- "GPL18588_hta20_Hs_ENTREZG.cdf" 
> hdr <- readCdfHeader(pathname)
> str(hdr)
List of 12
 $ ncols      : int 2680
 $ nrows      : int 2572
 $ nunits     : int 26194
 $ nqcunits   : int 0
 $ refseq     : chr ""
 $ chiptype   : chr "GPL18588_hta20_Hs_ENTREZG"
 $ filename   : chr "./GPL18588_hta20_Hs_ENTREZG.cdf"
 $ rows       : int 2572
 $ cols       : int 2680
 $ probesets  : int 26194
 $ qcprobesets: int 0
 $ reference  : chr ""

> qc <- readCdfQc(pathname)
> length(qc)
[1] 0

> data <- readCdf(pathname)
> length(data)
[1] 26194
```

Could it be that the first CDF is corrupt?

**Comment by HenrikBengtsson** [comment]
@benilton, I've tried to look at the problematic file manually, but cannot spot anything obvious, but my best guess it's corrupt (that has been the case in the past when affxparser/Fusion SDK core dumps like this.  Would you mind checking if other software and/orBioc packages can parse the problematic CDF?

**Comment by benilton** [comment]
Tried with affyio and it's a no-go.

Looks like the problem is the file itself.

Many thanks for your attention and apologies for the inconvenience,

b

**Comment by HenrikBengtsson** [comment]
Thanks for the following. Yeah, lets flag that file as "corrupt" for now.
