### ISSUE TITLE
Bug: inclusion of header files

### ISSUE THREAD

**Issue by kasperdanielhansen** [HenrikBengtsson/affxparser#21]
Email from Brian Ripley:

[Subject]
BioC packages affxparser flowCore rhdf5

[Body]
These now fail to install in R-devel as they include headers such as R.h from C++ code inside an extern "C" block.  That has been failing in some pre-release compilers and we have switched to including C++ headers such as cmath (rather than math.h).  Installation now fails with current versions of common C++ compilers such as g++ and clang++.

In the case of rhd5, HandleList.cpp includes HandleList.h inside such a block, and it includes R.h.

These packages are used from CRAN packages, so please correct at least in the BioC trunk ASAP.

**Comment by HenrikBengtsson** [comment]
Travis CI confirms that affxparser no longer installs on R devel due to ["template with C linkage" errors](https://travis-ci.org/HenrikBengtsson/affxparser/jobs/87249834#L1707-L1845), e.g.
```sh
In file included from /home/travis/R-bin/R-devel/lib/R/include/R.h:36:0,
                 from R_affx_cel_parser.cpp:10:
/usr/include/c++/4.6/cmath: In function ‘double std::abs(double)’:
/usr/include/c++/4.6/cmath:82:17: error: declaration of C function ‘double std::abs(double)’ conflicts with
/usr/include/c++/4.6/cstdlib:139:3: error: previous declaration ‘long int std::abs(long int)’ here
[...]
/usr/include/c++/4.6/cmath:813:3: error: template with C linkage
/usr/include/c++/4.6/cmath:822:3: error: template with C linkage
/usr/include/c++/4.6/cmath:831:3: error: template with C linkage
make: *** [R_affx_cel_parser.o] Error 1
ERROR: compilation failed for package ‘affxparser’
```

**Comment by kasperdanielhansen** [comment]
Seems to me that this is something that should be easy to fix if you fully understand it.  Perhaps get in touch with authors of flowCore and rhdf5?

**Comment by kasperdanielhansen** [comment]
Fixed in version 1.43.1, I think.  Henrik, if fixed, could you push it to Bioconductor svn.  All I have done is fixing it on Github.

**Comment by HenrikBengtsson** [comment]
Thxs.

**Comment by HenrikBengtsson** [comment]
Should this be backported (before it's too late) to current release brand for R 3.2.x which will be used from CRAN testing for another year?

**Comment by HenrikBengtsson** [comment]
Or is this truly only for R (>= 3.3.0)?

**Comment by kasperdanielhansen** [comment]
I think this is 3.3.0, since the issue arises with the new GCC in the new
Rtools intended for 3.3.0.

On Mon, Apr 25, 2016 at 11:17 AM, Henrik Bengtsson <notifications@github.com

**Comment by HenrikBengtsson** [comment]
OK. Let's leave it as is then. In the worst case scenario, it should be fixable even after the freeze if needed.
