### ISSUE TITLE
CLEANUP: Delete 10-year old R_affx_test_*_cmdline.cpp files?

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/affxparser#26]
Under [`src/`](https://github.com/HenrikBengtsson/affxparser/tree/master/src) we have the following "test/prototyping" command-line programs that hasn't been modified in the last 10 years:

1. [R_affx_test_bpmap_cmdline.cpp](https://github.com/HenrikBengtsson/affxparser/blob/master/src/R_affx_test_bpmap_cmdline.cpp)
2. [R_affx_test_cdfwriter_cmdline.cpp](https://github.com/HenrikBengtsson/affxparser/blob/master/src/R_affx_test_cdfwriter_cmdline.cpp)
3. [R_affx_test_celwriter_cmdline.cpp](https://github.com/HenrikBengtsson/affxparser/blob/master/src/R_affx_test_celwriter_cmdline.cpp)
4. [R_affx_test_cmd_line.cpp](https://github.com/HenrikBengtsson/affxparser/blob/master/src/R_affx_test_cmd_line.cpp)

I doubt they are of any use.  Can we delete these?

**Comment by kasperdanielhansen** [comment]
Yes

Best,
Kasper
(Sent from my phone.)

**Comment by HenrikBengtsson** [comment]
Done (in `develop` branch).
