### ISSUE TITLE
error: use of undeclared identifier 'finite'; did you mean 'isfinite'? (was: OSX 10.9 (Mavericks) build generates concerning compile warnings)

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/affxparser#6]
When building affxparser on OSX 10.9 (Mavericks), there lots of warnings are reported while compiling the native code, e.g.

```
fusion_sdk/calvin_files/data/src/CDFProbeSetInformation.cpp:109:15: 
warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
        if (groupIdx < 0 || groupIdx >= groupCnt)
```

and

```
fusion_sdk/util/Util.cpp:856:10: 
warning: 'finite' is deprecated: first deprecated in OS X 10.9 [-Wdeprecated-declarations]
  isOk = finite(x);
```

You can see them all at http://master.bioconductor.org/checkResults/devel/bioc-LATEST/affxparser/morelia-checksrc.html

These warnings do neither show up on other OSX version nor on other OSes, but they do look worrisome.  Except from one:

```
R_affx_cdf_parser.cpp:169:31: warning: expression result unused [-Wunused-value]
        for(int i = 0; i++; i < length(unitIndices)) {
```

they're all related to `fusion_sdk/` code.

@kasperdanielhansen, since you've navigated the Fusion SDK code more than I and are way more OSX savvy than I am, is this something you could look into?

**Comment by HenrikBengtsson** [comment]
Updated link to check results: http://master.bioconductor.org/checkResults/devel/bioc-LATEST/affxparser/oaxaca-checksrc.html

**Comment by bjmt** [comment]
Hi,

Not sure if I should make a new issue instead of dredging up an old one but the `'finite' is deprecated` warning has now become an error (undeclared identifier) on my macbook pro M1 (macOS 11.2.3) when trying to compile the package. Using Apple clang 12.0.0 for arm64 with R 4.0.4. Please let me know if there's any other info I can provide that might be helpful.

**Comment by HenrikBengtsson** [comment]
Just for the record, Simon Urbanek also reports/confirms that there is now an "error: use of undeclared identifier 'finite'; did you mean 'isfinite'?" and followed up with a confirmation that `finite()` is not part of C99.

From: Simon Urbanek
Date: Wed, Sep 8, 2021 at 3:23 AM
Subject: affxparser fails on macOS arm64
To: Henrik Bengtsson

Henrik,

I'm trying to get more CRAN packages to build on the M1 setup and this involves getting BioC into shape and I noticed that affxparser fails with:

clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -Ifusion_sdk/calvin_files/array/src -Ifusion_sdk/calvin_files/data/src -Ifusion_sdk/calvin_files/exception/src -Ifusion_sdk/calvin_files/fusion/src -Ifusion_sdk/calvin_files/fusion/src/GCOSAdapter -Ifusion_sdk/calvin_files/fusion/src/CalvinAdapter -Ifusion_sdk/calvin_files/parameter/src -Ifusion_sdk/calvin_files/parsers/src -Ifusion_sdk/calvin_files/portability/src -Ifusion_sdk/calvin_files/template/src -Ifusion_sdk/calvin_files/utils/src -Ifusion_sdk/calvin_files/writers/src -Ifusion_sdk/file -Ifusion_sdk/file/TsvFile -Ifusion_sdk/portability -Ifusion_sdk/util -Ifusion_sdk -D_USE_MEM_MAPPING_  -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wno-sign-compare -O0 -c fusion_sdk/util/Util.cpp -o fusion_sdk/util/Util.o
fusion_sdk/util/Util.cpp:858:10: error: use of undeclared identifier 'finite'; did you mean 'isfinite'?
  isOk = finite(x);
         ^~~~~~
         isfinite
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/math.h:441:1: note: 'isfinite' declared here
isfinite(_A1 __lcpp_x) _NOEXCEPT
^
1 error generated.
make: *** [fusion_sdk/util/Util.o] Error 1
ERROR: compilation failed for package ‘affxparser’
* removing ‘/Volumes/Builds/packages/big-sur-arm64/extralib/4.1/affxparser’

FWIW there is also

clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -Ifusion_sdk/calvin_files/array/src -Ifusion_sdk/calvin_files/data/src -Ifusion_sdk/calvin_files/exception/src -Ifusion_sdk/calvin_files/fusion/src -Ifusion_sdk/calvin_files/fusion/src/GCOSAdapter -Ifusion_sdk/calvin_files/fusion/src/CalvinAdapter -Ifusion_sdk/calvin_files/parameter/src -Ifusion_sdk/calvin_files/parsers/src -Ifusion_sdk/calvin_files/portability/src -Ifusion_sdk/calvin_files/template/src -Ifusion_sdk/calvin_files/utils/src -Ifusion_sdk/calvin_files/writers/src -Ifusion_sdk/file -Ifusion_sdk/file/TsvFile -Ifusion_sdk/portability -Ifusion_sdk/util -Ifusion_sdk -D_USE_MEM_MAPPING_  -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wno-sign-compare -O0 -c fusion_sdk/util/AffxConv.cpp -o fusion_sdk/util/AffxConv.o
fusion_sdk/util/AffxConv.cpp:124:8: warning: self-comparison always evaluates to false [-Wtautological-compare]
        if (i != i) {return "nan";}
              ^
1 warning generated.


Since there are dependencies, it would be nice if there was a way to fix that.

Thanks,
Simon

From: Simon Urbanek
Date: Wed, Sep 8, 2021 at 2:48 AM
Subject: Re: affxparser fails on macOS arm64
To: Henrik Bengtsson

FWIW I looked and it is a genuine bug - math.h and cmath only define isfinite(x) [defined since C99] - there is no such thing as finite(x) in the standards. The other warning is a benign dead code since it works on an integer which can never be NaN.

It means I was able to get it to work by hand with PKG_CXXFLAGS=-Dfinite=isfinite but for the package to build on BioC you probably want to fix it in the sources.

Cheers,
Simon

**Comment by HenrikBengtsson** [comment]
Fixed and live now.
